-- Create extensions schema
CREATE SCHEMA IF NOT EXISTS extensions;
GRANT USAGE ON SCHEMA extensions TO bouncer;

-- Create bouncer schema
CREATE SCHEMA bouncer AUTHORIZATION bouncer_admin;

GRANT USAGE ON SCHEMA bouncer TO bouncer;

GRANT SELECT ON ALL TABLES IN SCHEMA bouncer TO bouncer;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA bouncer TO bouncer_admin;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA bouncer TO bouncer;

ALTER DEFAULT PRIVILEGES IN SCHEMA bouncer GRANT SELECT ON TABLES TO bouncer;
ALTER DEFAULT PRIVILEGES IN SCHEMA bouncer GRANT USAGE, SELECT ON SEQUENCES TO bouncer;
ALTER DEFAULT PRIVILEGES IN SCHEMA bouncer GRANT INSERT, UPDATE, DELETE ON TABLES TO bouncer_admin;